first/account/urls.py
from django.urls import path
from . import views


app_name = 'register'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name = 'user_register'),
    path('login/', views.UserLoginView.as_view(), name = 'user_login'),
    path('logout/', views.UserLogoutView.as_view(), name = 'user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name = 'user_profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>', views.UserUnfollowView.as_view(), name='user_unfollow'),
]

first/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [

    path('', views.HomeView.as_view(), name = 'home'),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name = 'post_detail'),
    path('post/delete/<int:post_id>/', views.PostDeleteView.as_view(), name = 'post_delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name = 'post_update'),
    path('post/create/', views.PostCreateView.as_view(), name = 'post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name = 'add_reply'),
    path('like/<int:post_id>/', views.PostLikeView.as_view(), name = 'post_like'),
    
]

first/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert- {{msg.tags}}">{{msg}}</p>
    {% endfor %}
{% endif %}

first/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
        </li>
        {% if request.user.is_authenticated %}
            <li>
              <a class="nav-link active" aria-current="page" href="{% url 'register:user_logout' %}">logout</a>
            </li>
            <li>
              <a class="nav-link active" aria-current="page" href="{% url 'register:user_profile' request.user.id %}">Profile</a>
            </li>
        {% else %}
            <li>
              <a class="nav-link active" aria-current="page" href="{% url 'register:user_register' %}">Register</a>
            </li>
            <li>
              <a class="nav-link active" aria-current="page" href="{% url 'register:user_login' %}">Login</a>
            </li>
            
        {% endif %}
    </div>
  
</nav>